// This is a fixed version of the dealers.ts file with updated subcategory values

import { Dealer } from '@/types';

export const dealers: Dealer[] = [
  // OPC 43 Dealers
  {
    id: 1,
    dealerCode: 'KCS', // Khopoli Construction Suppliers
    name: "Khopoli Construction Suppliers",
    rating: 4.8,
    reviewCount: 45,
    location: "Khopoli, Maharashtra",
    distance: "2.5",
    price: 340,
    unit: "per bag",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=300&fit=crop",
    features: ["GPS Tracking", "Quality Assured", "Bulk Orders"],
    category: "cement",
    subcategory: "opc-43",
    businessType: "Manufacturer & Wholesaler",
    yearEstablished: "2010",
    description: "Leading manufacturer and supplier of premium quality construction materials with over a decade of experience in the industry. We specialize in OPC and PPC cement, serving both retail and bulk customers.",
    deliveryArea: "All over Maharashtra",
    certifications: ["ISO 9001:2015", "BIS Certified", "ISO 14001:2015"],
    responseRate: 98,
    avgResponseTime: "2 hours",
    orderFulfillmentRate: 95,
    logo: "https://via.placeholder.com/150"
  },
  {
    id: 2,
    dealerCode: 'LCM', // Lonavala Construction Material
    name: "Lonavala Construction Material Dealer",
    rating: 4.5,
    reviewCount: 32,
    location: "Lonavala, Maharashtra",
    distance: "5.7",
    price: 335,
    unit: "per bag",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=300&fit=crop",
    features: ["Free Delivery", "24/7 Support", "Bulk Discounts"],
    category: "cement",
    subcategory: "opc-53",
    businessType: "Wholesale Distributor",
    yearEstablished: "2015",
    description: "Trusted wholesale distributor of construction materials with a strong network across Lonavala and surrounding areas. We provide quality products with reliable delivery services.",
    deliveryArea: "Lonavala, Khandala, Kamshet",
    certifications: ["ISO 9001:2015", "BIS Certified"],
    responseRate: 95,
    avgResponseTime: "4 hours",
    orderFulfillmentRate: 92,
    logo: "https://via.placeholder.com/150/0000FF/808080"
  },
  // Concrete Blocks Dealer
  {
    id: 3,
    dealerCode: 'KCB', // Khopoli Concrete Blocks
    name: "Khopoli Construction Suppliers",
    rating: 4.7,
    reviewCount: 38,
    location: "Khopoli, Maharashtra",
    distance: "2.5",
    price: 45,
    unit: "per piece",
    deliveryTime: "1-2 Days",
    verified: true,
    image: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&h=600&fit=crop",
    features: ["Standard Size", "High Strength", "Fire Resistant"],
    category: "blocks",
    subcategory: "concrete",
    businessType: "Manufacturer & Supplier",
    yearEstablished: "2010",
    description: "Leading manufacturer of high-quality concrete blocks in Khopoli. Our blocks are known for their durability and strength, making them ideal for all types of construction projects.",
    deliveryArea: "50km radius around Khopoli",
    certifications: ["ISO 9001:2015", "BIS Certified"],
    responseRate: 97,
    avgResponseTime: "3 hours",
    orderFulfillmentRate: 96,
    logo: "https://via.placeholder.com/150"
  },
  // River Sand Dealer
  {
    id: 4,
    dealerCode: 'KRS', // Khopoli River Sand
    name: "Khopoli Construction Suppliers",
    rating: 4.6,
    reviewCount: 42,
    location: "Khopoli, Maharashtra",
    distance: "2.5",
    price: 2200,
    unit: "per brass",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1600880292203-757bb62f4a50?w=800&h=600&fit=crop",
    features: ["Natural River Sand", "Washed & Graded", "Silt Free"],
    category: "sand",
    subcategory: "river-sand",
    businessType: "Wholesale Supplier",
    yearEstablished: "2010",
    description: "Premium quality river sand sourced from trusted locations. Our sand is thoroughly washed and graded to ensure the highest quality for construction purposes.",
    deliveryArea: "Khopoli and surrounding areas",
    certifications: ["ISO 9001:2015", "Mines Department Certified"],
    responseRate: 96,
    avgResponseTime: "2 hours",
    orderFulfillmentRate: 98,
    logo: "https://via.placeholder.com/150"
  },
  // Red Clay Bricks Dealer
  {
    id: 5,
    dealerCode: 'KMS', // Khopoli Material Suppliers
    name: "Khopoli Construction Suppliers",
    rating: 4.5,
    reviewCount: 35,
    location: "Khopoli, Maharashtra",
    distance: "2.5",
    price: 8,
    unit: "per piece",
    deliveryTime: "1-2 Days",
    verified: true,
    image: "https://images.unsplash.com/photo-1600607687939-ce4289c73b78?w=800&h=600&fit=crop",
    features: ["High Compressive Strength", "Uniform Size", "Thermal Insulation"],
    category: "bricks",
    subcategory: "red-clay",
    businessType: "Manufacturer & Supplier",
    yearEstablished: "2010",
    description: "High-quality red clay bricks manufactured using traditional methods for superior strength and durability. Ideal for all types of construction projects.",
    deliveryArea: "100km radius around Khopoli",
    certifications: ["ISO 9001:2015", "BIS Certified"],
    responseRate: 95,
    avgResponseTime: "4 hours",
    orderFulfillmentRate: 97,
    logo: "https://via.placeholder.com/150"
  },
  // TMT Bars Dealer
  {
    id: 6,
    dealerCode: 'KTM', // Khopoli TMT
    name: "Khopoli Construction Suppliers",
    rating: 4.8,
    reviewCount: 50,
    location: "Khopoli, Maharashtra",
    distance: "2.5",
    price: 72500,
    unit: "per ton",
    deliveryTime: "2-3 Days",
    verified: true,
    image: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=800&h=600&fit=crop",
    features: ["Fe 500D Grade", "Earthquake Resistant", "Corrosion Resistant"],
    category: "steel",
    subcategory: "tmt-bars",
    businessType: "Authorized Dealer",
    yearEstablished: "2010",
    description: "Authorized dealer of premium grade TMT bars known for their superior strength and durability. Our TMT bars are manufactured using the latest technology for enhanced safety and performance.",
    deliveryArea: "All over Maharashtra",
    certifications: ["ISO 9001:2015", "BIS Certified", "ISO 14001:2015"],
    responseRate: 99,
    avgResponseTime: "1 hour",
    orderFulfillmentRate: 100,
    logo: "https://via.placeholder.com/150"
  },
  // Fine Stone Dust Dealer
  {
    id: 7,
    dealerCode: 'KCD', // Khopoli Cement Dealer
    name: "Khopoli Construction Suppliers",
    rating: 4.4,
    reviewCount: 28,
    location: "Khopoli, Maharashtra",
    distance: "2.5",
    price: 1200,
    unit: "per brass",
    deliveryTime: "1-2 Days",
    verified: true,
    image: "https://images.unsplash.com/photo-1592394533824-9440e0e0f668?w=800&h=600&fit=crop",
    features: ["Dust Free", "Well Graded", "Ideal for Flooring"],
    category: "stone-dust",
    subcategory: "fine-stone-dust",
    businessType: "Supplier",
    yearEstablished: "2010",
    description: "Premium quality fine stone dust perfect for construction and flooring applications. Our stone dust is free from impurities and provides excellent compaction.",
    deliveryArea: "Khopoli and nearby areas",
    certifications: ["ISO 9001:2015"],
    responseRate: 94,
    avgResponseTime: "5 hours",
    orderFulfillmentRate: 95,
    logo: "https://via.placeholder.com/150"
  },
  // 10mm Aggregate Dealer
  {
    id: 8,
    dealerCode: 'TBD', // Talegaon Building Depot
    name: "Khopoli Construction Suppliers",
    rating: 4.6,
    reviewCount: 33,
    location: "Khopoli, Maharashtra",
    distance: "2.5",
    price: 1800,
    unit: "per brass",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    features: ["10mm Size", "Hard Granite", "Washed & Graded"],
    category: "aggregate",
    subcategory: "10mm",
    businessType: "Wholesale Supplier",
    yearEstablished: "2010",
    description: "High-quality 10mm aggregate perfect for concrete mixing and construction purposes. Our aggregates are thoroughly washed and graded to ensure consistency and quality.",
    deliveryArea: "75km radius around Khopoli",
    certifications: ["ISO 9001:2015", "BIS Certified"],
    responseRate: 96,
    avgResponseTime: "3 hours",
    orderFulfillmentRate: 97,
    logo: "https://via.placeholder.com/150"
  },
  // 10mm Rubblestone Dealer
  {
    id: 9,
    dealerCode: 'KSD', // Kamshet Supplier Direct
    name: "Khopoli Construction Suppliers",
    rating: 4.5,
    reviewCount: 30,
    location: "Khopoli, Maharashtra",
    distance: "2.5",
    price: 1600,
    unit: "per brass",
    deliveryTime: "1-2 Days",
    verified: true,
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop",
    features: ["10mm Size", "Hard Granite", "Perfect for Landscaping"],
    category: "rubblestone",
    subcategory: "10mm-rubble",
    businessType: "Supplier",
    yearEstablished: "2010",
    description: "Premium quality 10mm rubblestone ideal for landscaping, drainage, and construction projects. Our rubblestone is durable and provides excellent drainage properties.",
    deliveryArea: "50km radius around Khopoli",
    certifications: ["ISO 9001:2015"],
    responseRate: 95,
    avgResponseTime: "4 hours",
    orderFulfillmentRate: 96,
    logo: "https://via.placeholder.com/150"
  },
  // Lonavala Construction Material Dealer - Fly Ash Bricks
  {
    id: 238,
    dealerCode: 'LFB', // Lonavala Fly Ash Bricks
    name: "Lonavala Construction Material Dealer",
    rating: 4.6,
    reviewCount: 28,
    location: "Lonavala, Maharashtra",
    distance: "5.7",
    price: 8,
    unit: "per piece",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1587583770464-0dfb846df031?w=400&h=300&fit=crop",
    features: ["Eco-friendly", "High Strength", "Thermal Insulation"],
    category: "bricks",
    subcategory: "fly-ash",
    businessType: "Wholesale Distributor",
    yearEstablished: "2015",
    description: "Premium quality fly ash bricks for sustainable construction. Our bricks are lightweight, durable, and environmentally friendly.",
    deliveryArea: "Lonavala, Khandala, Kamshet",
    certifications: ["ISO 9001:2015", "BIS Certified"],
    responseRate: 96,
    avgResponseTime: "3 hours",
    orderFulfillmentRate: 94,
    logo: "https://via.placeholder.com/150"
  },
  // Lonavala Construction Material Dealer - AAC Blocks
  {
    id: 239,
    dealerCode: 'LAC', // Lonavala AAC
    name: "Lonavala Construction Material Dealer",
    rating: 4.7,
    reviewCount: 35,
    location: "Lonavala, Maharashtra",
    distance: "5.7",
    price: 85,
    unit: "per sq.ft",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1587583770464-0dfb846df031?w=400&h=300&fit=crop",
    features: ["Lightweight", "Thermal Insulation", "Sound Proof"],
    category: "blocks",
    subcategory: "aac",
    businessType: "Wholesale Distributor",
    yearEstablished: "2015",
    description: "High-quality AAC blocks for modern construction. Our blocks are lightweight, fire-resistant, and provide excellent thermal insulation.",
    deliveryArea: "Lonavala, Khandala, Kamshet",
    certifications: ["ISO 9001:2015", "BIS Certified"],
    responseRate: 95,
    avgResponseTime: "3 hours",
    orderFulfillmentRate: 95,
    logo: "https://via.placeholder.com/150"
  },
  // Lonavala Construction Material Dealer - Red Sand
  {
    id: 240,
    dealerCode: 'LRS', // Lonavala Red Sand
    name: "Lonavala Construction Material Dealer",
    rating: 4.4,
    reviewCount: 25,
    location: "Lonavala, Maharashtra",
    distance: "5.7",
    price: 45,
    unit: "per cubic foot",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe9632335ba?w=400&h=300&fit=crop",
    features: ["Natural Red Color", "Fine Texture", "Ideal for Plastering"],
    category: "sand",
    subcategory: "red-sand",
    businessType: "Wholesale Distributor",
    yearEstablished: "2015",
    description: "Premium quality red sand suitable for all construction purposes. Our red sand is clean, well-graded, and perfect for plastering work.",
    deliveryArea: "Lonavala, Khandala, Kamshet",
    certifications: ["ISO 9001:2015"],
    responseRate: 94,
    avgResponseTime: "4 hours",
    orderFulfillmentRate: 93,
    logo: "https://via.placeholder.com/150"
  },
  // Lonavala Construction Material Dealer - Binding Wire
  {
    id: 241,
    dealerCode: 'LCM', // Lonavala Construction Material
    name: "Lonavala Construction Material Dealer",
    rating: 4.5,
    reviewCount: 30,
    location: "Lonavala, Maharashtra",
    distance: "5.7",
    price: 650,
    unit: "per kg",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1605271437061-80c7a1a4a2e9?w=400&h=300&fit=crop",
    features: ["High Tensile Strength", "Corrosion Resistant", "Flexible"],
    category: "steel",
    subcategory: "binding-wire",
    businessType: "Wholesale Distributor",
    yearEstablished: "2015",
    description: "Premium quality binding wire for construction and reinforcement work. Our binding wire is strong, durable, and rust-resistant.",
    deliveryArea: "Lonavala, Khandala, Kamshet",
    certifications: ["ISO 9001:2015", "BIS Certified"],
    responseRate: 95,
    avgResponseTime: "3 hours",
    orderFulfillmentRate: 94,
    logo: "https://via.placeholder.com/150"
  },
  // Lonavala Construction Material Dealer - Coarse Stone Dust
  {
    id: 242,
    dealerCode: 'LCS', // Lonavala Coarse Stone
    name: "Lonavala Construction Material Dealer",
    rating: 4.3,
    reviewCount: 22,
    location: "Lonavala, Maharashtra",
    distance: "5.7",
    price: 35,
    unit: "per cubic foot",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe9632335ba?w=400&h=300&fit=crop",
    features: ["Well-Graded", "Durable", "Ideal for Concrete Mix"],
    category: "stone-dust",
    subcategory: "coarse-stone-dust",
    businessType: "Wholesale Distributor",
    yearEstablished: "2015",
    description: "High-quality coarse stone dust for construction and landscaping. Our stone dust is clean, well-graded, and perfect for various construction applications.",
    deliveryArea: "Lonavala, Khandala, Kamshet",
    certifications: ["ISO 9001:2015"],
    responseRate: 93,
    avgResponseTime: "4 hours",
    orderFulfillmentRate: 92,
    logo: "https://via.placeholder.com/150"
  },
  // Lonavala Construction Material Dealer - 20mm Aggregate
  {
    id: 243,
    dealerCode: 'L20', // Lonavala 20mm
    name: "Lonavala Construction Material Dealer",
    rating: 4.6,
    reviewCount: 27,
    location: "Lonavala, Maharashtra",
    distance: "5.7",
    price: 40,
    unit: "per cubic foot",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe9632335ba?w=400&h=300&fit=crop",
    features: ["20mm Size", "Hard Granite", "Ideal for Concrete"],
    category: "aggregate",
    subcategory: "20mm",
    businessType: "Wholesale Distributor",
    yearEstablished: "2015",
    description: "Premium quality 20mm aggregate for concrete and construction. Our aggregate is clean, hard, and free from impurities.",
    deliveryArea: "Lonavala, Khandala, Kamshet",
    certifications: ["ISO 9001:2015"],
    responseRate: 95,
    avgResponseTime: "3 hours",
    orderFulfillmentRate: 94,
    logo: "https://via.placeholder.com/150"
  },
  // Lonavala Construction Material Dealer - 20mm Rubblestone
  {
    id: 244,
    dealerCode: 'LRB', // Lonavala Rubblestone
    name: "Lonavala Construction Material Dealer",
    rating: 4.5,
    reviewCount: 24,
    location: "Lonavala, Maharashtra",
    distance: "5.7",
    price: 45,
    unit: "per cubic foot",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe9632335ba?w=400&h=300&fit=crop",
    features: ["20mm Size", "Natural Stone", "Drainage Friendly"],
    category: "rubblestone",
    subcategory: "20mm-rubble",
    businessType: "Wholesale Distributor",
    yearEstablished: "2015",
    description: "Premium quality 20mm rubblestone for landscaping and drainage. Our rubblestone is durable, natural, and provides excellent drainage properties.",
    deliveryArea: "Lonavala, Khandala, Kamshet",
    certifications: ["ISO 9001:2015"],
    responseRate: 94,
    avgResponseTime: "4 hours",
    orderFulfillmentRate: 93,
    logo: "https://via.placeholder.com/150"
  },
  // Kamshet Material Supplier - PPC Cement
  {
    id: 245,
    dealerCode: 'KMS2', // Kamshet Material Supplier 2
    name: "Kamshet Material Supplier",
    rating: 4.6,
    reviewCount: 38,
    location: "Kamshet, Maharashtra",
    distance: "8.2",
    price: 320,
    unit: "per bag",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&h=300&fit=crop",
    features: ["Pozzolanic Cement", "High Strength", "Durable"],
    category: "cement",
    subcategory: "ppc",
    businessType: "Wholesale Supplier",
    yearEstablished: "2018",
    description: "High-quality PPC cement for all construction needs. Our PPC cement offers excellent workability, durability, and resistance to chemical attacks.",
    deliveryArea: "Kamshet, Lonavala, Khandala",
    certifications: ["ISO 9001:2015", "BIS Certified"],
    responseRate: 96,
    avgResponseTime: "2 hours",
    orderFulfillmentRate: 95,
    logo: "https://via.placeholder.com/150"
  },
  // Kamshet Material Supplier - Coarse Sand
  {
    id: 246,
    dealerCode: 'KMS', // Kamshet Material Supplier
    name: "Kamshet Material Supplier",
    rating: 4.5,
    reviewCount: 32,
    location: "Kamshet, Maharashtra",
    distance: "8.2",
    price: 38,
    unit: "per cubic foot",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe9632335ba?w=400&h=300&fit=crop",
    features: ["Coarse Grade", "Well-Graded", "Ideal for Concrete"],
    category: "sand",
    subcategory: "coarse",
    businessType: "Wholesale Supplier",
    yearEstablished: "2018",
    description: "Premium quality coarse sand for construction and concrete work. Our sand is clean, well-graded, and free from impurities.",
    deliveryArea: "Kamshet, Lonavala, Khandala",
    certifications: ["ISO 9001:2015"],
    responseRate: 95,
    avgResponseTime: "3 hours",
    orderFulfillmentRate: 94,
    logo: "https://via.placeholder.com/150"
  },
  // Kamshet Material Supplier - Steel Rods
  {
    id: 247,
    dealerCode: 'KSR', // Kamshet Steel Rods
    name: "Kamshet Material Supplier",
    rating: 4.7,
    reviewCount: 42,
    location: "Kamshet, Maharashtra",
    distance: "8.2",
    price: 75,
    unit: "per kg",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1605271437061-80c7a1a4a2e9?w=400&h=300&fit=crop",
    features: ["High Tensile Strength", "Corrosion Resistant", "IS 1786 Certified"],
    category: "steel",
    subcategory: "steel-rods",
    businessType: "Wholesale Supplier",
    yearEstablished: "2018",
    description: "High-quality steel rods for construction and reinforcement. Our steel rods are durable, strong, and meet all industry standards.",
    deliveryArea: "Kamshet, Lonavala, Khandala",
    certifications: ["ISO 9001:2015", "BIS Certified"],
    responseRate: 97,
    avgResponseTime: "2 hours",
    orderFulfillmentRate: 96,
    logo: "https://via.placeholder.com/150"
  },
  // Kamshet Material Supplier - 40mm Aggregate
  {
    id: 248,
    dealerCode: 'K40', // Kamshet 40mm
    name: "Kamshet Material Supplier",
    rating: 4.4,
    reviewCount: 28,
    location: "Kamshet, Maharashtra",
    distance: "8.2",
    price: 42,
    unit: "per cubic foot",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe9632335ba?w=400&h=300&fit=crop",
    features: ["40mm Size", "Hard Granite", "Ideal for Concrete"],
    category: "aggregate",
    subcategory: "40mm",
    businessType: "Wholesale Supplier",
    yearEstablished: "2018",
    description: "Premium quality 40mm aggregate for heavy-duty concrete work. Our aggregate is clean, hard, and free from impurities.",
    deliveryArea: "Kamshet, Lonavala, Khandala",
    certifications: ["ISO 9001:2015"],
    responseRate: 95,
    avgResponseTime: "3 hours",
    orderFulfillmentRate: 94,
    logo: "https://via.placeholder.com/150"
  },
  // Kamshet Material Supplier - 40mm Rubblestone
  {
    id: 249,
    dealerCode: 'KRB', // Kamshet Rubblestone
    name: "Kamshet Material Supplier",
    rating: 4.5,
    reviewCount: 26,
    location: "Kamshet, Maharashtra",
    distance: "8.2",
    price: 48,
    unit: "per cubic foot",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe9632335ba?w=400&h=300&fit=crop",
    features: ["40mm Size", "Natural Stone", "Drainage Friendly"],
    category: "rubblestone",
    subcategory: "40mm-rubble",
    businessType: "Wholesale Supplier",
    yearEstablished: "2018",
    description: "Premium quality 40mm rubblestone for landscaping and drainage. Our rubblestone is durable, natural, and provides excellent drainage properties.",
    deliveryArea: "Kamshet, Lonavala, Khandala",
    certifications: ["ISO 9001:2015"],
    responseRate: 94,
    avgResponseTime: "3 hours",
    orderFulfillmentRate: 93,
    logo: "https://via.placeholder.com/150"
  },
  // Talegaon Builderox - White Cement
  {
    id: 250,
    dealerCode: 'TBL2', // Talegaon Builderox 2
    name: "Talegaon Builderox",
    rating: 4.7,
    reviewCount: 45,
    location: "Talegaon, Maharashtra",
    distance: "12.5",
    price: 650,
    unit: "per bag",
    deliveryTime: "1 Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1566919769-1b7a3f3b4d8b?w=400&h=300&fit=crop",
    features: ["Premium White", "High Whiteness", "Decorative Finish"],
    category: "cement",
    subcategory: "white-cement",
    businessType: "Building Materials Supplier",
    yearEstablished: "2017",
    description: "Premium quality white cement for decorative and architectural applications. Our white cement provides a smooth, bright white finish for all your construction needs.",
    deliveryArea: "Talegaon, Chakan, Dehu Road",
    certifications: ["ISO 9001:2015", "BIS Certified"],
    responseRate: 95,
    avgResponseTime: "4 hours",
    orderFulfillmentRate: 94,
    logo: "https://via.placeholder.com/150"
  },
  // Talegaon Builderox - Fine Sand
  {
    id: 251,
    dealerCode: 'TBL', // Talegaon Builderox
    name: "Talegaon Builderox",
    rating: 4.5,
    reviewCount: 36,
    location: "Talegaon, Maharashtra",
    distance: "12.5",
    price: 42,
    unit: "per cubic foot",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe9632335ba?w=400&h=300&fit=crop",
    features: ["Fine Grade", "Smooth Texture", "Ideal for Plastering"],
    category: "sand",
    subcategory: "fine",
    businessType: "Building Materials Supplier",
    yearEstablished: "2017",
    description: "Premium quality fine sand for plastering and finishing works. Our fine sand is clean, well-graded, and perfect for smooth finishes.",
    deliveryArea: "Talegaon, Chakan, Dehu Road",
    certifications: ["ISO 9001:2015"],
    responseRate: 94,
    avgResponseTime: "5 hours",
    orderFulfillmentRate: 93,
    logo: "https://via.placeholder.com/150"
  },
  // Talegaon Builderox - Dust Aggregate
  {
    id: 252,
    dealerCode: 'TDA', // Talegaon Dust Aggregate
    name: "Talegaon Builderox",
    rating: 4.4,
    reviewCount: 29,
    location: "Talegaon, Maharashtra",
    distance: "12.5",
    price: 38,
    unit: "per cubic foot",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe9632335ba?w=400&h=300&fit=crop",
    features: ["Fine Dust", "Well-Graded", "Ideal for Filling"],
    category: "aggregate",
    subcategory: "dust",
    businessType: "Building Materials Supplier",
    yearEstablished: "2017",
    description: "High-quality dust aggregate for filling and leveling applications. Our dust aggregate is clean, well-graded, and perfect for various construction needs.",
    deliveryArea: "Talegaon, Chakan, Dehu Road",
    certifications: ["ISO 9001:2015"],
    responseRate: 93,
    avgResponseTime: "5 hours",
    orderFulfillmentRate: 92,
    logo: "https://via.placeholder.com/150"
  },
  // Vadgoan Pro Builder - RMC
  {
    id: 253,
    dealerCode: 'VRM', // Vadgoan RMC
    name: "Vadgoan Pro Builder",
    rating: 4.8,
    reviewCount: 52,
    location: "Vadgaon, Maharashtra",
    distance: "15.3",
    price: 4200,
    unit: "per cubic meter",
    deliveryTime: "On Schedule",
    verified: true,
    image: "https://images.unsplash.com/photo-1605152276907-5f0dd994cdb9?w=400&h=300&fit=crop",
    features: ["Ready Mix", "Consistent Quality", "Time-Saving"],
    category: "cement",
    subcategory: "rmc",
    businessType: "RMC Supplier",
    yearEstablished: "2016",
    description: "Premium quality Ready Mix Concrete (RMC) for all your construction needs. Our RMC ensures consistent quality, strength, and durability for your projects.",
    deliveryArea: "Vadgaon, Pimpri, Chinchwad",
    certifications: ["ISO 9001:2015", "ISO 14001:2015", "BIS Certified"],
    responseRate: 97,
    avgResponseTime: "2 hours",
    orderFulfillmentRate: 96,
    logo: "https://via.placeholder.com/150"
  },
  // Vadgoan Pro Builder - Filtered Sand
  {
    id: 254,
    dealerCode: 'VFS', // Vadgoan Filtered Sand
    name: "Vadgoan Pro Builder",
    rating: 4.6,
    reviewCount: 41,
    location: "Vadgaon, Maharashtra",
    distance: "15.3",
    price: 48,
    unit: "per cubic foot",
    deliveryTime: "Same Day",
    verified: true,
    image: "https://images.unsplash.com/photo-1587854692152-cbe9632335ba?w=400&h=300&fit=crop",
    features: ["Double Washed", "Silt Free", "Premium Quality"],
    category: "sand",
    subcategory: "filtered",
    businessType: "Construction Material Supplier",
    yearEstablished: "2016",
    description: "Premium quality filtered sand for all construction and masonry work. Our filtered sand is thoroughly washed, free from silt and organic impurities, ensuring superior bonding and finish.",
    deliveryArea: "Vadgaon, Pimpri, Chinchwad",
    certifications: ["ISO 9001:2015"],
    responseRate: 95,
    avgResponseTime: "3 hours",
    orderFulfillmentRate: 94,
    logo: "https://via.placeholder.com/150"
  }
];
